[package]
name = "wvr-midi"
version = "0.1.2"
authors = ["gurke.club <contact@gurke.club>"]
edition = "2018"

[dependencies]
midir = "0.5"
wmidi = "4.0"
anyhow = "1.0"
wvr-data = {git = "https://github.com/gurkeclub/wvr-data.git", branch="main"}
